# Generated by Django 6.1 on 2026-09-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Пустой товар', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.ManyToManyField(related_name='products', through='logistic.StockProduct', to='logistic.stock'),
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='Пустой склад', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
